server:
  port: 8082

spring:
  application:
    name: processing-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/orders_db # Conexão com o banco do Docker
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: processing-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*" # Permite a desserialização do modelo de pacotes confiáveis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans