spring.application.name=SpringFrameworkApplication

# Configurações do Banco de Dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ebac_produtos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=bldRkqL4CWOoPI6DxaFRTA==

# Configuração do Hibernate / JPA
# Mantém os dados ao fechar (update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true