server:
  port: 8761

spring:
  application:
    name: discovery-server
eureka:
  client:
    register-with-eureka: false # Impede que o próprio servidor tente se registrar nele mesmo
    fetch-registry: false