# Configurações de Conexão com o MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/streaming_platform?serverTimezone=UTC
spring.datasource.username=root

spring.datasource.password=minhasenhaquenaoquerocompartilharassimdegraca

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurações do Hibernate/JPA
# Como já criamos o script do banco, 'validate' garante que o mapeamento bata com o DB sem sobrescrever nada
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações do Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs